import {
  a1,
  a2,
  a3,
  a4,
  a5,
  b1,
  b2,
  b3,
  b4,
  b5,
  c1,
  c2,
  c3,
  c4,
  c5,
  d1,
  d2,
  d3,
  d4,
  d5,
  m1,
  m2,
  m3,
  m4,
  m5,
  o1,
  o2,
  o3,
  o4,
  o5,
} from "../assets";

const gifts = [
  {
    image: a1,
    name: "Blue Pendant",
    description: "Timeless elegance in a stunning blue pendant.",
    category: "Anniversary",
    cost: 350,
  },
  {
    image: a2,
    name: "Perfume",
    description: "Captivating fragrance for an unforgettable presence.",
    category: "Anniversary",
    cost: 350,
  },
  {
    image: a3,
    name: "Teddy Bear",
    description: "Cuddly companion for moments of warmth and comfort.",
    category: "Anniversary",
    cost: 350,
  },
  {
    image: a4,
    name: "Couple Figurine",
    description: "Express your love with a beautifully crafted figurine.",
    category: "Anniversary",
    cost: 350,
  },
  {
    image: a5,
    name: "Crystal",
    description: "Sparkling giant crystal, a symbol of enduring love.",
    category: "Anniversary",
    cost: 350,
  },
  {
    image: b1,
    name: "Metal Cannon Model",
    description: "A unique and memorable keepsake.",
    category: "Birthday",
    cost: 350,
  },
  {
    image: b2,
    name: "Sneakers",
    description: "Step into style with these trendy and comfortable sneakers.",
    category: "Birthday",
    cost: 350,
  },
  {
    image: b3,
    name: "Wrist Watch",
    description: "Elegant wristwatch: a timeless gift for any occasion.",
    category: "Birthday",
    cost: 350,
  },
  {
    image: b4,
    name: "Lego Set",
    description: "Unleash creativity with a vibrant Lego building set.",
    category: "Birthday",
    cost: 350,
  },
  {
    image: b5,
    name: "Barbie Doll",
    description: "Charm and playfulness in a classic Barbie doll.",
    category: "Birthday",
    cost: 350,
  },
  {
    image: c1,
    name: "Toddler Toy Set",
    description: "A bundle of joy for little ones.",
    category: "Christmas",
    cost: 350,
  },
  {
    image: c2,
    name: "Teddy Bear",
    description: "Warm hugs await with this festive teddy bear.",
    category: "Christmas",
    cost: 350,
  },
  {
    image: c3,
    name: "Snow Globe",
    description: "Capture the magic with a whimsical penguin snow globe.",
    category: "Christmas",
    cost: 350,
  },
  {
    image: c4,
    name: "Comics Set",
    description: "Adventure awaits in this exciting comics set.",
    category: "Christmas",
    cost: 350,
  },
  {
    image: c5,
    name: "Football",
    description: "Score a goal with the perfect football for festive fun.",
    category: "Christmas",
    cost: 350,
  },
  {
    image: d1,
    name: "Shoulder Bracelet",
    description: "Graceful adornment for a touch of ethnic charm.",
    category: "Diwali",
    cost: 350,
  },
  {
    image: d2,
    name: "Terracotta Glasses",
    description: "Sip in style with these charming terracotta glasses.",
    category: "Diwali",
    cost: 350,
  },
  {
    image: d3,
    name: "Traditional Pillows",
    description: "Enhance your space with the comfort of traditional pillows.",
    category: "Diwali",
    cost: 350,
  },
  {
    image: d4,
    name: "Heritage Rugs",
    description: "Bring heritage into your home with these exquisite rugs.",
    category: "Diwali",
    cost: 350,
  },
  {
    image: d5,
    name: "Ethnic Painting",
    description: "Add regal charm with an ethnic painting of a princess.",
    category: "Diwali",
    cost: 350,
  },
  {
    image: m1,
    name: "Flower Vase",
    description: "A beautiful addition to their new home.",
    category: "Marriage",
    cost: 350,
  },
  {
    image: m2,
    name: "Espresso Machine",
    description: "A gift to brew happiness in their mornings.",
    category: "Marriage",
    cost: 350,
  },
  {
    image: m3,
    name: "Cutlery Set",
    description: "Elevate their dining experience with this elegant set.",
    category: "Marriage",
    cost: 350,
  },
  {
    image: m4,
    name: "Designer Lamp",
    description: "Illuminate their space with a touch of sophistication.",
    category: "Marriage",
    cost: 350,
  },
  {
    image: m5,
    name: "Dutch Oven",
    description: "A versatile kitchen companion for their culinary journey.",
    category: "Marriage",
    cost: 350,
  },
  {
    image: o1,
    name: "Headphones",
    description: "Immerse in music with top-notch headphones.",
    category: "Others",
    cost: 350,
  },
  {
    image: o2,
    name: "Vintage Typewriter",
    description: "Capture thoughts on a classic vintage typewriter.",
    category: "Others",
    cost: 350,
  },
  {
    image: o3,
    name: "Basketball",
    description: "Bounce into fun with this sporty basketball.",
    category: "Others",
    cost: 350,
  },
  {
    image: o4,
    name: "Wooden Bench Set",
    description: "Create cozy moments with a charming wooden bench set.",
    category: "Others",
    cost: 350,
  },
  {
    image: o5,
    name: "Stationery Set",
    description: "Unleash creativity with a thoughtful stationery set.",
    category: "Others",
    cost: 350,
  },
];

const headers = [
  { content: "“Curated for your loved ones...”", id: "giftsel" },
  { content: "“In moments, find occasions...”", id: "occasionsel" },
];

const occasions = [
  { Name: "Anniversary" },
  { Name: "Birthday" },
  { Name: "Christmas" },
  { Name: "Diwali" },
  { Name: "Marriage" },
  { Name: "Others" },
];

export { gifts, headers, occasions };
